import { useState, useEffect, useRef } from 'react';
import html2canvas from 'html2canvas';

export default function SkillCard() {
  const [jobsData, setJobsData] = useState([]);
  const [query, setQuery] = useState('');
  const [filtered, setFiltered] = useState([]);
  const [selectedJob, setSelectedJob] = useState(null);
  const [loadError, setLoadError] = useState('');
  const cardRef = useRef(null);

  useEffect(() => {
    fetch('/skill_jobs.json')
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        setJobsData(data);
      })
      .catch((err) => {
        console.error('Failed to load skill jobs:', err);
        setLoadError('Failed to load job data. Please refresh.');
      });
  }, []);

  const handleSearch = (value) => {
    setQuery(value);
    if (!value.trim()) {
      setFiltered([]);
      return;
    }
    const matches = jobsData.filter((job) =>
      job.title.toLowerCase().includes(value.toLowerCase())
    );
    setFiltered(matches.slice(0, 10));
  };

  const showCard = (job) => {
    setSelectedJob(job);
    setFiltered([]);
    setQuery(job.title);
  };

  const handlePrint = () => {
    if (!cardRef.current) return;
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Skill Card - ${selectedJob.title}</title>
          <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
          <style>
            body { font-family: "Space Grotesk", sans-serif; padding: 2rem; color: #0f172a; }
            h2 { color: #0f766e; margin-bottom: 0.5rem; }
            .code { color: #64748b; font-size: 0.9rem; margin-bottom: 1rem; }
            .category { color: #3b82f6; font-size: 0.85rem; font-weight: 600; margin-bottom: 1rem; }
            h4 { color: #0f766e; margin: 1rem 0 0.5rem; }
            .skills { display: flex; flex-wrap: wrap; gap: 8px; }
            .skill-tag {
              background: rgba(45,212,191,0.15); color: #0f766e;
              padding: 6px 14px; border-radius: 999px; font-size: 0.9rem;
              border: 1px solid rgba(45,212,191,0.4);
            }
            .links { margin-top: 1rem; }
            .links a {
              display: inline-block; margin: 4px 8px 4px 0; padding: 8px 16px;
              background: #2dd4bf; color: white; text-decoration: none;
              border-radius: 0.5rem; font-size: 0.9rem;
            }
            .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; font-size: 0.8rem; color: #94a3b8; }
          </style>
        </head>
        <body>
          ${cardRef.current.innerHTML}
          <div class="footer">Generated by AISPIRE — AI-Enabled NCO Semantic Search</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="flex-1 flex flex-col md:flex-row min-h-[calc(100vh-140px)]">
      {/* Left Panel - Search */}
      <div className="md:w-[400px] md:min-w-[300px] bg-white/95 backdrop-blur-sm p-8 flex flex-col justify-center border-r border-slate-200 shadow-[4px_0_20px_rgba(0,0,0,0.04)]">
        <h1 className="text-2xl font-bold text-slate-900 mb-3">Skill Card Generator</h1>
        <p className="text-sm text-slate-500 mb-6">
          Type a job title to instantly see the key skills and recommended courses to level up your career.
        </p>

        {loadError && <p className="text-red-500 text-sm mb-4">{loadError}</p>}

        <div className="relative">
          <input
            type="text"
            value={query}
            onChange={(e) => handleSearch(e.target.value)}
            placeholder="Search job title (e.g. Electrician, Nurse, Plumber)..."
            className="w-full px-4 py-3 border border-slate-200 rounded-xl outline-none focus:border-primary focus:ring-2 focus:ring-primary/20 text-slate-900 placeholder-slate-400"
          />

          {filtered.length > 0 && (
            <div className="absolute z-50 w-full mt-1 bg-white border border-slate-200 rounded-xl shadow-xl max-h-[250px] overflow-y-auto">
              {filtered.map((job) => (
                <div
                  key={job.code + job.title}
                  onMouseDown={(e) => {
                    e.preventDefault();
                    showCard(job);
                  }}
                  className="px-4 py-3 cursor-pointer text-sm text-slate-700 hover:bg-primary/10 transition-colors border-b border-slate-50 last:border-0"
                >
                  <span className="font-medium">{job.title}</span>
                  <span className="text-xs text-slate-400 ml-2">({job.category})</span>
                </div>
              ))}
            </div>
          )}
        </div>

        {jobsData.length > 0 && (
          <p className="text-xs text-slate-400 mt-3">{jobsData.length} jobs available with skill data</p>
        )}

        {query.trim() && filtered.length === 0 && jobsData.length > 0 && !selectedJob && (
          <p className="text-xs text-amber-600 mt-2">No jobs found matching "{query}". Try: Electrician, Nurse, Plumber, Data Entry</p>
        )}
      </div>

      {/* Right Panel - Card */}
      <div className="flex-1 flex items-center justify-center p-8 bg-gradient-to-br from-primary/5 to-background-light">
        {selectedJob ? (
          <div className="bg-white/95 rounded-2xl p-8 max-w-[600px] w-full shadow-xl border border-slate-200 animate-[fadeIn_0.4s_ease-in-out]">
            <div ref={cardRef}>
              <h2 className="text-2xl font-bold text-slate-900 mb-1">{selectedJob.title}</h2>
              <p className="text-sm text-slate-500 mb-1">NCO Code: {selectedJob.code}</p>
              {selectedJob.category && (
                <p className="text-sm font-semibold text-accent-blue mb-4">Category: {selectedJob.category}</p>
              )}

              <h4 className="font-bold text-[#0f766e] mb-2 mt-4">Skills Required:</h4>
              <div className="flex flex-wrap gap-2">
                {selectedJob.skills.map((skill) => (
                  <span
                    key={skill}
                    className="px-3 py-1.5 rounded-full text-sm bg-primary/15 text-[#0f766e] border border-primary/40 hover:scale-105 hover:bg-primary/25 transition-transform cursor-default"
                  >
                    {skill}
                  </span>
                ))}
              </div>

              <h4 className="font-bold text-[#0f766e] mb-2 mt-6">Suggested Courses:</h4>
              <div className="links flex flex-wrap gap-2">
                {selectedJob.nptel_course && (
                  <a
                    href={selectedJob.nptel_course}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-block px-4 py-2 bg-primary text-white rounded-lg text-sm font-semibold hover:opacity-90 hover:-translate-y-0.5 transition-all no-underline"
                  >
                    NPTEL
                  </a>
                )}
                {selectedJob.swayam_course && (
                  <a
                    href={selectedJob.swayam_course}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-block px-4 py-2 bg-primary text-white rounded-lg text-sm font-semibold hover:opacity-90 hover:-translate-y-0.5 transition-all no-underline"
                  >
                    SWAYAM
                  </a>
                )}
                {selectedJob.youtube_link && (
                  <a
                    href={selectedJob.youtube_link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-block px-4 py-2 bg-red-500 text-white rounded-lg text-sm font-semibold hover:opacity-90 hover:-translate-y-0.5 transition-all no-underline"
                  >
                    YouTube
                  </a>
                )}
              </div>
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={handlePrint}
                className="flex items-center gap-1.5 px-5 py-2.5 bg-slate-700 text-white rounded-xl font-semibold hover:opacity-90 hover:-translate-y-0.5 transition-all"
              >
                <span className="material-symbols-outlined text-base">print</span>
                Print
              </button>
              <button
                onClick={async () => {
                  if (!cardRef.current) return;
                  const canvas = await html2canvas(cardRef.current, {
                    scale: 2,
                    backgroundColor: '#ffffff',
                    useCORS: true,
                  });
                  const link = document.createElement('a');
                  link.download = `SkillCard_${selectedJob.title.replace(/[^a-zA-Z0-9]/g, '_')}.png`;
                  link.href = canvas.toDataURL('image/png');
                  link.click();
                }}
                className="flex items-center gap-1.5 px-5 py-2.5 bg-accent-blue text-white rounded-xl font-semibold hover:opacity-90 hover:-translate-y-0.5 transition-all"
              >
                <span className="material-symbols-outlined text-base">download</span>
                Download
              </button>
            </div>
          </div>
        ) : (
          <div className="text-center text-slate-400">
            <span className="material-symbols-outlined text-6xl mb-4 block opacity-30">badge</span>
            <p className="text-lg font-medium">Search and select a job to generate a Skill Card</p>
            <p className="text-sm mt-2">Try typing: Electrician, Nurse, Plumber, Data Entry Operator</p>
          </div>
        )}
      </div>
    </div>
  );
}
